version: '3'
services:
  frontend:
    build:
      context: ./react_app
    ports:
      - "3000:3000"
    volumes:
      - ./react_app:/app
    command: npm start

  backend:
    build:
      context: .  # Build from the current directory
    ports:
      - "5000:5000"
    volumes:
      - ./visualizer:/app
    command: python app.py
